# Generated by Django 5.0.4 on 2024-09-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackingnumber",
            name="tracking_number",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
